name: build dev
on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * 1"  
  push:
    branches:
      - master
    paths:
      - dev/**

jobs:
  pushArm:
      name: "yolks:dev:${{ matrix.tag }}"
      runs-on: ubuntu-latest
      strategy:
        fail-fast: false
        matrix:
          tag:
            - fex
            - fex_rust
            - fex_fivem
            - fex_latest
      steps:
        - uses: actions/checkout@v3
        - uses: docker/setup-buildx-action@v2
          with:
            buildkitd-flags: --debug
        - name: Set up QEMU
          uses: docker/setup-qemu-action@v3
          with:
            platforms: arm64,amd64
            image: tonistiigi/binfmt:qemu-v7.0.0-28
        - uses: docker/login-action@v2
          with:
            username: ${{ secrets.REPOSITORY_OWNER }}
            password: ${{ secrets.REGISTRY_TOKEN }}
        - uses: docker/build-push-action@v4
          with:
            context: ./dev/${{ matrix.tag }}
            file: ./dev/${{ matrix.tag }}/Dockerfile
            platforms: linux/arm64
            push: true
            tags: |
               quintenqvd/pterodactyl_images:dev_${{ matrix.tag }}
