name: build dotnet
on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * 1"
  push:
    branches:
      - master
    paths:
      - dotnet/**
jobs:
  push:
    name: "yolks:dotnet_${{ matrix.tag }}"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        tag:
          - 3.1
          - 6
          - 7
    steps:
      - uses: actions/checkout@v2
      # Setup QEMU for ARM64 Build
      - uses: docker/setup-qemu-action@v1
      - uses: docker/setup-buildx-action@v1
        with:
          version: "v0.8.2"
          buildkitd-flags: --debug
      - uses: docker/login-action@v1
        with:
          username: ${{ secrets.REPOSITORY_OWNER }}
          password: ${{ secrets.REGISTRY_TOKEN }}
      - uses: docker/build-push-action@v3
        with:
          context: ./dotnet
          file: ./dotnet/${{ matrix.tag }}/Dockerfile
          platforms: linux/arm64,linux/amd64
          push: true
          tags: |
            quintenqvd/pterodactyl_images:dotnet_${{ matrix.tag }}
