name: build steamcmd
on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * 1"
  push:
    branches:
      - master
    paths:
      - steamcmd/**
jobs:
  push:
    name: "yolks:steamcmd_${{ matrix.tag }}"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        tag:
          - proton
    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-buildx-action@v2
        with:
          buildkitd-flags: --debug
      - uses: docker/login-action@v2
        with:
          username: ${{ secrets.REPOSITORY_OWNER }}
          password: ${{ secrets.REGISTRY_TOKEN }}
      - uses: docker/build-push-action@v4
        with:
          context: ./steamcmd/${{ matrix.tag }}
          file: ./steamcmd/${{ matrix.tag }}/Dockerfile
          platforms: linux/amd64
          push: true
          tags: |
            quintenqvd/pterodactyl_images:steamcmd_${{ matrix.tag }}
