name: build temp
on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * 1"
  push:
    branches:
      - master
    paths:
      - temp/**
jobs:
  # pushArm:
  #    name: "yolks:tempARM_${{ matrix.tag }}"
  #    runs-on: ubuntu-latest
  #    strategy:
  #      fail-fast: false
  #      matrix:
  #        tag:
  #          - wine
  #    steps:
  #      - uses: actions/checkout@v3
  #      - uses: docker/setup-buildx-action@v2
  #        with:
  #          version: "v0.8.2"
  #          buildkitd-flags: --debug
  #      - name: Set up QEMU
  #        uses: docker/setup-qemu-action@master
  #        with:
  #          platforms: arm64,amd64
  #      - name: Cache Docker layers
  #        uses: actions/cache@v3
  #        with:
  #          path: /tmp/.buildx-cache
  #          key: ${{ runner.os }}-buildx-${{ github.sha }}
  #          restore-keys: |
  #            ${{ runner.os }}-buildx-
  #      - uses: docker/login-action@v2
  #        with:
  #          username: ${{ secrets.REPOSITORY_OWNER }}
  #          password: ${{ secrets.REGISTRY_TOKEN }}
  #      - uses: docker/build-push-action@v4
  #        with:
  #          context: ./temp/${{ matrix.tag }}
  #          file: ./temp/${{ matrix.tag }}/Dockerfile
  #          platforms: linux/arm64
  #          cache-from: type=local,src=/tmp/.buildx-cache
  #          cache-to: type=local,dest=/tmp/.buildx-cache-new
  #          push: true
  #          tags: |
  #             quintenqvd/pterodactyl_images:temp_${{ matrix.tag }}


  pushAll:
     name: "yolks:tempALL_${{ matrix.tag }}"
     runs-on: ubuntu-latest
     strategy:
       fail-fast: false
       matrix:
         tag:
           - nodejs_16_dotnet_7
           - nodejs_16_dotnet_6
           - python_3_11_web
     steps:
       - uses: actions/checkout@v2
       - name: Set up QEMU
         uses: docker/setup-qemu-action@master
         with:
           platforms: arm64,amd64
       - uses: docker/setup-buildx-action@v2
         with:
           buildkitd-flags: --debug
       - uses: docker/login-action@v2
         with:
           username: ${{ secrets.REPOSITORY_OWNER }}
           password: ${{ secrets.REGISTRY_TOKEN }}
       - uses: docker/build-push-action@v4
         with:
           context: ./temp/${{ matrix.tag }}
           file: ./temp/${{ matrix.tag }}/Dockerfile
           platforms: linux/amd64,linux/arm64
           push: true
           tags: |
             quintenqvd/pterodactyl_images:temp_${{ matrix.tag }}
  pushAMD:
    name: "yolks:tempAMD_${{ matrix.tag }}"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        tag:
          - crystal
          - nodejs_18_puppeteer
    steps:
      - uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@master
        with:
          platforms: arm64,amd64
      - uses: docker/setup-buildx-action@v2
        with:
          buildkitd-flags: --debug
      - uses: docker/login-action@v2
        with:
          username: ${{ secrets.REPOSITORY_OWNER }}
          password: ${{ secrets.REGISTRY_TOKEN }}
      - uses: docker/build-push-action@v4
        with:
          context: ./temp/${{ matrix.tag }}
          file: ./temp/${{ matrix.tag }}/Dockerfile
          platforms: linux/amd64
          push: true
          tags: |
            quintenqvd/pterodactyl_images:temp_${{ matrix.tag }}
